### issue descripton
{describe what happened that resulted in the crash}

### how do you reproduce it?
{a step by step instruction on recreating the error, or a video with what keys you are pressing visualized}

### what is the expected result of the steps?
{what should have been the expected results?}

### what actually happened after doing the steps?
{show what actually happened after doing the steps. preferrably, paste the exception if the app had crashed.}

### how can this be fixed?
{how do you think this bug can be fixed?}
