#:schema ./schema.json
# relative schema location for ease

[interface]
tooltips = true
nerd_font = true
use_reactive_layout = true
show_progress_eta = false
show_progress_percentage = true
truncate_progress_file_path = false
show_line_numbers = true
show_hidden_files = false
allow_tab_nav = true
append_new_tabs = true
double_click_delay = 0.25
drive_watcher_frequency = 3.0
# yazi style is 5
# but it has more space
scrolloff = 3

[interface.image_viewer]
protocol = "Auto"
max_size = [4000, 4000]

[interface.font_preview]
max_size = [1000, 1000]
font_size = 50

[interface.preview_text]
error = "couldn't read this file! (\u00AC_\u00AC)" # ¬_¬
start = """
  ___ ___
 |  _| . |
 |_| |___|
  _ _ ___
 | | |  _|
  \\_/|_|
"""
font_text = """
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
oO08 iIlL1 g9qCQG a@ 5sS
{} [==>  ] (*) <> ~-+ /\\
"""

[interface.clock]
enabled = true
align = "left"

[interface.compact_mode]
buttons = true
panels = false

[interface.mime_rules]
"text/.*" = "text"
"application/(json|javascript|xml|raml\\+yaml)" = "text"
"application/x-(yaml|script|pem-file|subrip|typescript)" = "text"
"application/(mbox|ndjson|wine-extension-ini)" = "text"
"image/svg\\+xml" = "resvg"
"image/(avif|hei.|jxl)" = "image"
"image/.*" = "image"
"application/pdf" = "pdf"
"application/(zip|gzip|zstd|bzip2|vnd\\.rar)" = "archive"
"application/x-(xz|tar|gzip|bzip2|xz|rar|rar-compressed|7z-compressed)" = "archive"
"application/(rar|7z.*|tar|xz|bzip.*|lzma|compress|archive|cpio|arj|xar|ms-cab.*)" = "archive"
"application/(iso9660-image|qemu-disk|ms-wim|apple-diskimage)" = "archive"
"application/virtualbox-(vhd|vhdx)" = "archive"
"application/(debian.*-package|redhat-package-manager|rpm|android\\.package-archive)" = "archive"
"inode/directory" = "folder"
"font/.*" = "font"
"application/ms-opentype" = "font"
"application/font-.*" = "font"
"application/x-font-.*" = "font"
# inaccurately determined by puremagic (it isnt always magic)
"application/vnd.openxmlformats-officedocument.wordprocessingml.document" = "remime"

[settings]
copy_includes_metadata = true
use_recycle_bin = true

[settings.bulk_rename]
show_as_mapping = true

[settings.editor]
open_all_in_editor = false

[settings.editor.file]
run = "$EDITOR"
block = false
suspend = true

[settings.editor.folder]
run = "$EDITOR"
block = false
suspend = true

[settings.editor.bulk_rename]
run = "$EDITOR"
suspend = true

[metadata]
fields = [
  "type",
  "permissions",
  "size",
  "modified",
  "accessed",
  "created",
  "hidden",
]
datetime_format = "%Y-%m-%d %H:%M"
filesize_decimals = 1
filesize_suffix = "decimal"

[theme]
default = "nord"
preview = "nord"
transparent = false

[[custom_theme]]
name = "nord"
primary = "#88C0D0"
secondary = "#81A1C1"
accent = "#B48EAD"
foreground = "#D8DEE9"
background = "#2E3440"
success = "#A3BE8C"
warning = "#EBCB8B"
error = "#BF616A"
surface = "#3B4252"
panel = "#434C5E"
is_dark = true

[custom_theme.bar_gradient]
default = ["#88c0d0", "#5e81ac"]
error = ["#bf616a", "#d08770"]

[[custom_theme]]
name = "Dark Pink"
primary = "#FD7AFF"
secondary = "#000F85"
success = "#FF007B"
warning = "#250069"
error = "#300025"
accent = "#000000"
foreground = "#FFFFFF"
background = "#000000"
surface = "#FD7AFF"
panel = "#2b2b2b"
is_dark = true

[custom_theme.variables]
"block-cursor-background" = "#88C0D0"
"block-cursor-foreground" = "#2E3440"
"block-cursor-text-style" = "none"
"footer-key-foreground" = "#88C0D0"
"input-selection-background" = "#81a1c1 35%"
"button-color-foreground" = "#2E3440"
"button-focus-text-style" = "reverse"

[keys]
[keys."-app"]
"S" = "toggle_pinned_sidebar"
"I" = "toggle_preview_sidebar"
"F" = "toggle_footer"
"M" = "toggle_menu_wrapper"
"s" = "focus_toggle_pinned_sidebar"
"escape" = "focus_file_list"
"i" = "focus_toggle_preview_sidebar"
"ctrl+l" = "focus_toggle_path_switcher"
"#" = "focus_toggle_processes"
"c" = "focus_toggle_clipboard"
"m" = "focus_toggle_metadata"
"]" = "tab_next"
"[" = "tab_previous"
"t" = "tab_new"
"w" = "tab_close"
"?" = "show_keybinds"
"ctrl+p" = "command_palette"
"ctrl+z" = "suspend_process"
"q" = "quit"
"ctrl+q" = "quit"
[keys."FileList:focus"]
"left" = "up_tree"
"h" = "up_tree"
"H" = "bypass_up_tree"
"L" = "bypass_down_tree"

[keys."#file_list:focus"]
"P" = "toggle_pin"
"slash" = "focus_search"
"y" = "copy"
"ctrl+c" = "copy"
"p" = "paste"
"x" = "cut"
"d" = "delete"
"r" = "rename"
"f2" = "rename"
"ctrl+n" = "new"
"a" = "new"
"E" = "zip"
"ctrl+e" = "unzip"
"backspace" = "hist_previous"
"u" = "hist_previous"
"space" = "hist_next"
"v" = "toggle_visual"
"%" = "toggle_all"
"ctrl+a" = "toggle_all"
"shift+up" = "select_up"
"shift+down" = "select_down"
"shift+pageup" = "select_page_up"
"shift+pagedown" = "select_page_down"
"shift+home" = "select_home"
"shift+end" = "select_end"
"e" = "open_editor"
">" = "show_shell_screen"
[keys."PinnedSidebar:focus"]
"slash" = "focus_search"
[keys.PreviewContainer]
"ctrl+j" = "down"
"ctrl+k" = "up"
[keys."CopyPanelOptions:focus"]
"Y" = "open_popup"
"y" = "copy_to_rovr"
"p" = "copy_single_path"
"s" = "copy_to_system_clip"
"d" = "copy_current_directory"
[keys."SortOrderPopup:focus"]
"," = "open_popup"
"a" = "change_sort_order_name"
"e" = "change_sort_order_extension"
"n" = "change_sort_order_natural"
"s" = "change_sort_order_size"
"c" = "change_sort_order_created"
"m" = "change_sort_order_modified"
"d" = "change_sort_order_descending"

[keys."*:focus"]
"up" = "up"
"down" = "down"
"k" = "up"
"j" = "down"
"pageup" = "page_up"
"ctrl+b" = "page_up"
"pagedown" = "page_down"
"ctrl+f" = "page_down"
"home" = "home"
"g" = "home"
"end" = "end"
"G" = "end"
"l" = "select"
"right" = "select"
"enter" = "select"

[keys."-screen:DeleteFiles"]
"d" = "trash"
"x" = "delete"
"c" = "cancel"
[keys."-screen:FileNameConflict"]
"o" = "overwrite"
"s" = "skip"
"r" = "rename"
"c" = "cancel"
"a" = "dont_ask_again"
[keys."-screen:FileInUse"]
"r" = "retry"
"s" = "skip"
[keys."-screen:YesOrNo"]
"y" = "yes"
"n" = "no"
"a" = "dont_ask_again"
[keys."-screen:ModalSearchScreen"]
"escape" = "dismiss"
"up" = "focused=Input:previous_option"
"ctrl+k" = "focused=Input:previous_option"
"down" = "focused=Input:next_option"
"ctrl+j" = "focused=Input:next_option"

[plugins.zoxide]
enabled = true
keybinds = ["z"]
show_scores = false

[plugins.bat]
enabled = false
executable = "bat"

[plugins.fd]
enabled = true
keybinds = ["f"]
executable = "fd"
relative_paths = true
follow_symlinks = false
no_ignore_parent = false
default_filter_types = ["file", "directory"]

[plugins.rg]
enabled = true
keybinds = ["\\"]
executable = "rg"
case_sensitive = true
no_ignore_parent = false
follow_symlinks = false
search_hidden = false

[plugins.poppler]
enabled = true
threads = 1
use_pdftocairo = false
poppler_folder = ""
pdf_batch_size = 2

[plugins.file_one]
enabled = false
get_description = true
