# Sane stuff

[settings.bulk_rename]
show_as_mapping = true

[keys.general]
"P" = "toggle_pin"
"S" = "toggle_pinned_sidebar"
"I" = "toggle_preview_sidebar"
"F" = "toggle_footer"
"M" = "toggle_menu_wrapper"
"s" = "focus_toggle_pinned_sidebar"
"escape" = "focus_file_list"
"i" = "focus_toggle_preview_sidebar"
"ctrl+l" = "focus_toggle_path_switcher"
"ctrl+f" = "focus_search"
"p" = "focus_toggle_processes"
"c" = "focus_toggle_clipboard"
"m" = "focus_toggle_metadata"
"ctrl+left_square_brace" = "tab_next"
"ctrl+right_square_brace" = "tab_previous"
"ctrl+t" = "tab_new"
"ctrl+w" = "tab_close"
"f1" = "show_keybinds"
"ctrl+q" = "quit_app"
"ctrl+p" = "command_palette"
"ctrl+z" = "suspend_process"
"ctrl+d" = "plugin_zoxide"
"ctrl+g" = "plugin_fd"
"\\" = "plugin_rg"

[keys.normal]
"ctrl+c" = "copy"
"ctrl+v" = "paste"
"ctrl+x" = "cut"
"delete" = "delete"
"f2" = "rename"
"ctrl+n" = "new"
"E" = "zip"
"ctrl+e" = "unzip"
"up" = "up"
"down" = "down"
"left" = "up_tree"
"alt+up" = "up_tree"
"right" = "down_tree"
"enter" = "down_tree"
"shift+left" = "bypass_up_tree"
"shift+right" = "bypass_down_tree"
"pageup" = "page_up"
"pagedown" = "page_down"
"home" = "home"
"end" = "end"
"backspace" = "hist_previous"
"alt+left" = "hist_previous"
"alt+right" = "hist_next"
"ctrl+a" = "toggle_all"
"ctrl+space" = "toggle_visual"
"." = "toggle_hidden_files"
"insert" = "toggle_select_item"
"space" = "toggle_select_item"
"ctrl+o" = "open_editor"

[keys.select]
"shift+up" = "select_up"
"shift+down" = "select_down"
"shift+pageup" = "select_page_up"
"shift+pagedown" = "select_page_down"
"shift+home" = "select_home"
"shift+end" = "select_end"

[keys.extra_copy]
"C" = "open_popup"
"r" = "copy_to_rovr"
"p" = "copy_single_path"
"s" = "copy_to_system_clip"
"u" = "copy_current_directory"

[keys.change_sort_order]
"o" = "open_popup"
"a" = "name"
"e" = "extension"
"n" = "natural"
"s" = "size"
"c" = "created"
"m" = "modified"
"d" = "descending"

[keys.delete_files]
"d" = "trash"
"D" = "delete"
"escape" = "cancel"

[keys.filename_conflict]
"o" = "overwrite"
"s" = "skip"
"r" = "rename"
"escape" = "cancel"
"a" = "dont_ask_again"

[keys.file_in_use]
"r" = "retry"
"s" = "skip"
"escape" = "cancel"
"a" = "dont_ask_again"

[keys.filter_modal]
"escape" = "exit"
"down" = "down"
"up" = "up"

[keys.yes_or_no]
"y" = "yes"
"enter" = "yes"
"n" = "no"
"escape" = "no"
"a" = "dont_ask_again"
