# vim stuff

[settings.bulk_rename]
show_as_mapping = false

[keys.general]
"P" = "toggle_pin"
"S" = "toggle_pinned_sidebar"
"I" = "toggle_preview_sidebar"
"F" = "toggle_footer"
"M" = "toggle_menu_wrapper"
"s" = "focus_toggle_pinned_sidebar"
"escape" = "focus_file_list"
"i" = "focus_toggle_preview_sidebar"
"ctrl+l" = "focus_toggle_path_switcher"
"/" = "focus_search"
"#" = "focus_toggle_processes"
"c" = "focus_toggle_clipboard"
"m" = "focus_toggle_metadata"
"ctrl+j" = "tab_next"
"ctrl+k" = "tab_previous"
"n" = "tab_new"
"w" = "tab_close"
"?" = "show_keybinds"
"q" = "quit_app"
"ctrl+q" = "quit_app"
"ctrl+p" = "command_palette"
"ctrl+z" = "suspend_process"
"z" = "plugin_zoxide"
"f" = "plugin_fd"
"\\" = "plugin_rg"

[keys.normal]
"y" = "copy"
"p" = "paste"
"x" = "cut"
"d" = "delete"
"r" = "rename"
"o" = "new"
"E" = "zip"
"ctrl+e" = "unzip"
"k" = "up"
"up" = "up"
"j" = "down"
"down" = "down"
"h" = "up_tree"
"left" = "up_tree"
"l" = "down_tree"
"right" = "down_tree"
"enter" = "down_tree"
"H" = "bypass_up_tree"
"L" = "bypass_down_tree"
"ctrl+b" = "page_up"
"pageup" = "page_up"
"ctrl+f" = "page_down"
"pagedown" = "page_down"
"g" = "home"
"G" = "end"
"u" = "hist_previous"
"backspace" = "hist_previous"
"ctrl+r" = "hist_next"
"space" = "hist_next"
"v" = "toggle_visual"
"%" = "toggle_all"
"ctrl+a" = "toggle_all"
"full_stop" = "toggle_hidden_files"
"e" = "open_editor"

[keys.select]
"K" = "select_up"
"shift+up" = "select_up"
"J" = "select_down"
"shift+down" = "select_down"
"shift+pageup" = "select_page_up"
"shift+pagedown" = "select_page_down"
"shift+home" = "select_home"
"shift+end" = "select_end"
"shift+left" = "preview_select_left"
"shift+right" = "preview_select_right"

[keys.extra_copy]
"Y" = "open_popup"
"y" = "copy_to_rovr"
"c" = "copy_single_path"
"s" = "copy_to_system_clip"
"d" = "copy_current_directory"

[keys.change_sort_order]
"," = "open_popup"
"a" = "name"
"e" = "extension"
"n" = "natural"
"s" = "size"
"c" = "created"
"m" = "modified"
"d" = "descending"

[keys.delete_files]
"d" = "trash"
"x" = "delete"
"c" = "cancel"
"escape" = "cancel"

[keys.filename_conflict]
"o" = "overwrite"
"s" = "skip"
"r" = "rename"
"c" = "cancel"
"escape" = "cancel"
"a" = "dont_ask_again"

[keys.file_in_use]
"r" = "retry"
"s" = "skip"
"c" = "cancel"
"escape" = "cancel"
"a" = "dont_ask_again"

[keys.filter_modal]
"escape" = "exit"
"ctrl+j" = "down"
"down" = "down"
"ctrl+k" = "up"
"up" = "up"

[keys.yes_or_no]
"y" = "yes"
"n" = "no"
"escape" = "no"
"a" = "dont_ask_again"
