# Conventional GUI-style keybindings

[global]
"ctrl+q" = "app.quit"
"ctrl+p" = "app.command_palette"
"ctrl+z" = "app.suspend_process"

[main]
"S" = "toggle_pinned_sidebar"
"I" = "toggle_preview_sidebar"
"F" = "toggle_footer"
"M" = "toggle_menu_wrapper"
"s" = "focus_toggle_pinned_sidebar"
"escape" = "focus_file_list"
"i" = "focus_toggle_preview_sidebar"
"ctrl+l" = "focus_toggle_path_switcher"
"p" = "focus_toggle_processes"
"c" = "focus_toggle_clipboard"
"m" = "focus_toggle_metadata"
"ctrl+[" = "cycle_tab(1)"
"ctrl+]" = "cycle_tab(-1)"
"ctrl+t" = "tab_new"
"ctrl+w" = "tab_close"
"f1" = "show_keybinds"
">" = "show_shell_screen"
"ctrl+d" = "cd_zoxide"
"ctrl+g" = "search_fd"
"\\" = "search_rg"

[file_list]
"P" = "toggle_pin"
"ctrl+f" = "focus_search"
"ctrl+c" = "copy.to_rovr"
"ctrl+v" = "paste"
"ctrl+x" = "cut"
"delete" = "delete"
"f2" = "rename"
"ctrl+n" = "new"
"ctrl+shift+n" = "bulk_create"
"E" = "zip"
"ctrl+e" = "unzip"
"left" = "up_tree"
"alt+up" = "up_tree"
"shift+left" = "bypass_up_tree"
"shift+right" = "bypass_down_tree"
"backspace" = "hist_previous"
"alt+left" = "hist_previous"
"alt+right" = "hist_next"
"ctrl+space" = "toggle_visual"
"ctrl+a" = "toggle_all"
"." = "toggle_hidden_files"
"insert" = "toggle_select_item"
"space" = "toggle_select_item"
"shift+up" = "select_cursor(-1)"
"shift+down" = "select_cursor(1)"
"shift+pageup" = "select_cursor_page(-1)"
"shift+pagedown" = "select_cursor_page(1)"
"shift+home" = "select_home"
"shift+end" = "select_end"
"o" = "open"
"ctrl+o" = "open_editor"
"shift+f10" = "open_right_click_menu"
"C" = "copy.open_popup"
"," = "sort_order.open_popup"

[pinned_sidebar]
"ctrl+f" = "focus_search"

[lists]
"up" = "cursor(-1)"
"down" = "cursor(1)"
"right" = "select"
"enter" = "select"
"pageup" = "cursor_page(-1)"
"pagedown" = "cursor_page(1)"
"home" = "first"
"end" = "last"

[copy_menu]
"r" = "copy.to_rovr"
"p" = "copy.highlighted"
"s" = "copy.to_system_clip"
"u" = "copy.current_directory"

[sort_menu]
"a" = "sort_order.name"
"e" = "sort_order.extension"
"n" = "sort_order.natural"
"s" = "sort_order.size"
"c" = "sort_order.created"
"m" = "sort_order.modified"
"d" = "sort_order.descending"

[delete_files]
"d" = "trash"
"D" = "delete"
"escape" = "cancel"

[trash]
"r" = "restore"
"D" = "purge"
"E" = "empty"
"escape" = "cancel"

[filename_conflict]
"o" = "overwrite"
"s" = "skip"
"r" = "rename"
"escape" = "cancel"
"a" = "dont_ask_again"

[file_in_use]
"r" = "retry"
"s" = "skip"
"escape" = "cancel"
"a" = "toggle_dont_ask_again"

[filter_modal]
"escape" = "exit"
"down" = "cursor(1)"
"up" = "cursor(-1)"
"pageup" = "cursor_page(-1)"
"pagedown" = "cursor_page(1)"

[keybinds]
"ctrl+f" = "focus_search"
"f1" = "exit"

[yes_or_no]
"y" = "yes"
"enter" = "yes"
"n" = "no"
"escape" = "no"
"a" = "dont_ask_again"

[paste_drop]
"c" = "copy"
"m" = "move"
"escape" = "cancel"
