# Vim-style keybindings

[global]
"q" = "app.quit"
"ctrl+q" = "app.quit"
"ctrl+p" = "app.command_palette"
"ctrl+z" = "app.suspend_process"

[main]
"S" = "toggle_pinned_sidebar"
"I" = "toggle_preview_sidebar"
"F" = "toggle_footer"
"M" = "toggle_menu_wrapper"
"s" = "focus_toggle_pinned_sidebar"
"escape" = "focus_file_list"
"i" = "focus_toggle_preview_sidebar"
"ctrl+l" = "focus_toggle_path_switcher"
"#" = "focus_toggle_processes"
"c" = "focus_toggle_clipboard"
"m" = "focus_toggle_metadata"
"ctrl+j" = "cycle_tab(1)"
"ctrl+k" = "cycle_tab(-1)"
"n" = "tab_new"
"w" = "tab_close"
"?" = "show_keybinds"
">" = "show_shell_screen"
"z" = "cd_zoxide"
"f" = "search_fd"
"\\" = "search_rg"

[file_list]
"P" = "toggle_pin"
"/" = "focus_search"
"y" = "copy.to_rovr"
"p" = "paste"
"x" = "cut"
"d" = "delete"
"r" = "rename"
"a" = "new"
"A" = "bulk_create"
"E" = "zip"
"ctrl+e" = "unzip"
"left" = "up_tree"
"h" = "up_tree"
"H" = "bypass_up_tree"
"L" = "bypass_down_tree"
"backspace" = "hist_previous"
"u" = "hist_previous"
"ctrl+r" = "hist_next"
"space" = "hist_next"
"v" = "toggle_visual"
"%" = "toggle_all"
"ctrl+a" = "toggle_all"
"." = "toggle_hidden_files"
"shift+up" = "select_cursor(-1)"
"K" = "select_cursor(-1)"
"shift+down" = "select_cursor(1)"
"J" = "select_cursor(1)"
"shift+pageup" = "select_cursor_page(-1)"
"shift+pagedown" = "select_cursor_page(1)"
"shift+home" = "select_home"
"shift+end" = "select_end"
"o" = "open"
"e" = "open_editor"
"shift+f10" = "open_right_click_menu"
"Y" = "copy.open_popup"
"," = "sort_order.open_popup"

[pinned_sidebar]
"/" = "focus_search"

[lists]
"up" = "cursor(-1)"
"k" = "cursor(-1)"
"down" = "cursor(1)"
"j" = "cursor(1)"
"right" = "select"
"l" = "select"
"enter" = "select"
"pageup" = "cursor_page(-1)"
"ctrl+b" = "cursor_page(-1)"
"pagedown" = "cursor_page(1)"
"ctrl+f" = "cursor_page(1)"
"home" = "first"
"g" = "first"
"end" = "last"
"G" = "last"

[copy_menu]
"y" = "copy.to_rovr"
"c" = "copy.highlighted"
"s" = "copy.to_system_clip"
"d" = "copy.current_directory"

[sort_menu]
"a" = "sort_order.name"
"e" = "sort_order.extension"
"n" = "sort_order.natural"
"s" = "sort_order.size"
"c" = "sort_order.created"
"m" = "sort_order.modified"
"d" = "sort_order.descending"

[delete_files]
"d" = "trash"
"x" = "delete"
"c" = "cancel"
"escape" = "cancel"

[trash]
"r" = "restore"
"x" = "purge"
"E" = "empty"
"c" = "cancel"
"escape" = "cancel"

[filename_conflict]
"o" = "overwrite"
"s" = "skip"
"r" = "rename"
"c" = "cancel"
"escape" = "cancel"
"a" = "dont_ask_again"

[file_in_use]
"r" = "retry"
"s" = "skip"
"c" = "cancel"
"escape" = "cancel"
"a" = "toggle_dont_ask_again"

[filter_modal]
"escape" = "exit"
"down" = "cursor(1)"
"ctrl+j" = "cursor(1)"
"up" = "cursor(-1)"
"ctrl+k" = "cursor(-1)"
"pageup" = "cursor_page(-1)"
"ctrl+b" = "cursor_page(-1)"
"pagedown" = "cursor_page(1)"
"ctrl+f" = "cursor_page(1)"

[inputs]
"left" = "cursor_left"
"shift+left" = "cursor_left(True)"
"ctrl+left" = "cursor_left_word"
"ctrl+shift+left" = "cursor_left_word(True)"
"right" = "cursor_right"
"shift+right" = "cursor_right(True)"
"ctrl+right" = "cursor_right_word"
"ctrl+shift+right" = "cursor_right_word(True)"
"backspace" = "delete_left"
"ctrl+shift+a" = "select_all"
"home" = "home"
"ctrl+a" = "home"
"end" = "end"
"ctrl+e" = "end"
"shift+home" = "home(True)"
"shift+end" = "end(True)"
"delete" = "delete_right"
"ctrl+d" = "delete_right"
"enter" = "submit"
"ctrl+w" = "delete_left_word"
"ctrl+u" = "delete_left_all"
"super+backspace" = "delete_left_all"
"ctrl+backspace" = "delete_right_word"
"alt+backspace" = "delete_right_word"
"ctrl+k" = "delete_right_all"
"ctrl+x" = "cut"
"ctrl+c" = "copy"
"super+c" = "copy"
"ctrl+v" = "paste"

[keybinds]
"/" = "focus_search"
"?" = "exit"

[yes_or_no]
"y" = "yes"
"n" = "no"
"escape" = "no"
"a" = "dont_ask_again"

[paste_drop]
"c" = "copy"
"m" = "move"
"escape" = "cancel"
